### ISSUE TITLE
Can't seem to get GCF deploy working on nested routed

### ISSUE THREAD

**Issue by acoyfellow** [sanderhahn/gcloud-sapper#1]
For the root + about page, a SSR works as expected.. The /blog, and every sub page, I get a 500's

On the [index.js](https://github.com/sanderhahn/gcloud-sapper/blob/master/index.js) file, the `req.headers.host` value seems to come in as `127.0.0.1:8080` for those routes. Still investigating, but I'm eager to get this working.

**Comment by sanderhahn** [comment]
Are you using Sapper on Google Cloud Functions? Needed some fixes to get `fetch` working: https://github.com/sanderhahn/gcloud-sapper#fetch-fix Have you already tried that?

**Comment by sanderhahn** [comment]
Deployed this repository here: https://europe-west1-sander.cloudfunctions.net/sapper/ and that seems to work with the changes.
